"use strict";
const express = require("express");
const { authMiddleware } = require("../../../middleware/auth");
const { requirePermission } = require("../../../middleware/rbac");
const controller = require("./success_story.controller");
const validator = require("./success_story.validator");
const MODULE = "MOD-26";
const router = express.Router();
router.use(authMiddleware);
router.get("/", requirePermission(MODULE, "view"), controller.list);
router.get("/:id", requirePermission(MODULE, "view"), controller.get);
router.post("/", requirePermission(MODULE, "create"), validator.create, controller.create);
router.patch("/:id", requirePermission(MODULE, "edit"), validator.update, controller.update);
router.post("/:id/sign-off", requirePermission(MODULE, "approve"), controller.signOff);
router.post("/:id/publish", requirePermission(MODULE, "approve"), controller.publish);
router.post("/:id/unpublish", requirePermission(MODULE, "approve"), controller.unpublish);
module.exports = { basePath: "/success-stories", feature: null, router };
