"use strict";
const express = require("express");
const { authMiddleware } = require("../../../middleware/auth");
const { requirePermission } = require("../../../middleware/rbac");
const controller = require("./opportunity.controller");
const validator = require("./opportunity.validator");
const MODULE = "MOD-24";
const router = express.Router();
router.use(authMiddleware);
router.get("/board", requirePermission(MODULE, "view"), controller.board);
router.get("/stages", requirePermission(MODULE, "view"), controller.stages);
router.get("/", requirePermission(MODULE, "view"), controller.list);
router.get("/:id", requirePermission(MODULE, "view"), controller.get);
router.post("/", requirePermission(MODULE, "create"), validator.create, controller.create);
router.patch("/:id", requirePermission(MODULE, "edit"), validator.update, controller.update);
router.post("/:id/move", requirePermission(MODULE, "edit"), validator.move, controller.move);
router.post("/:id/win", requirePermission(MODULE, "edit"), validator.win, controller.win);
router.post("/:id/lose", requirePermission(MODULE, "edit"), controller.lose);
module.exports = { basePath: "/opportunities", feature: null, router };
