"use strict";
const express = require("express");
const { authMiddleware } = require("../../../middleware/auth");
const { requirePermission } = require("../../../middleware/rbac");
const controller = require("./marketing_campaign.controller");
const validator = require("./marketing_campaign.validator");
const MODULE = "MOD-22";
const router = express.Router();
router.use(authMiddleware);
router.get("/subscribers", requirePermission(MODULE, "view"), controller.subscribers);
router.post("/subscribers", requirePermission(MODULE, "create"), validator.subscribe, controller.subscribe);
router.post("/subscribers/unsubscribe", requirePermission(MODULE, "edit"), validator.unsubscribe, controller.unsubscribe);
router.get("/", requirePermission(MODULE, "view"), controller.list);
router.get("/:id", requirePermission(MODULE, "view"), controller.get);
router.post("/", requirePermission(MODULE, "create"), validator.create, controller.create);
router.post("/:id/transition", requirePermission(MODULE, "edit"), validator.transition, controller.transition);
module.exports = { basePath: "/campaigns", feature: null, router };
