-- 0500 — Index the foreign keys. 290 of 344 had none.
--
-- Audit DATA 2.2 (High). Derived by parsing the DDL: 344 foreign keys across
-- the tenant schema, 54 whose referencing column already leads an index (a
-- primary key, a unique, or an explicit index), 290 with nothing.
--
-- WHY AN UNINDEXED FK COSTS MORE THAN A SLOW JOIN
--
--   1. Every DELETE or UPDATE of a parent key makes Postgres check each child
--      table for referencing rows. With no index that is a SEQUENTIAL SCAN of
--      the child, per parent row. 0498 just changed nine of these to RESTRICT,
--      which makes the check happen on every attempted delete rather than
--      cascading — so the cost lands more often, not less.
--
--   2. The check takes a lock while it scans. On a large child table that turns
--      a routine parent delete into a visible stall.
--
--   3. Every "show me the children of this parent" query — which is most of the
--      detail views in the product — is a full scan of the child table.
--
-- Same reasoning as 0496 (created_at): plain CREATE INDEX rather than
-- CONCURRENTLY, because the migrator sends each file as one multi-statement
-- simple query and Postgres wraps that in an implicit transaction block, where
-- CONCURRENTLY cannot run. Build time scales with current row count, so this is
-- cheapest applied now.
--
-- IF NOT EXISTS throughout: re-runnable, and safe on a tenant provisioned after
-- this was written.


CREATE INDEX IF NOT EXISTS idx_access_review_completed_by ON access_review (completed_by);
CREATE INDEX IF NOT EXISTS idx_access_review_created_by ON access_review (created_by);
CREATE INDEX IF NOT EXISTS idx_access_review_entry_decided_by ON access_review_entry (decided_by);
CREATE INDEX IF NOT EXISTS idx_access_review_entry_user_id ON access_review_entry (user_id);
CREATE INDEX IF NOT EXISTS idx_advance_client_id ON advance (client_id);
CREATE INDEX IF NOT EXISTS idx_advance_dossier_id ON advance (dossier_id);
CREATE INDEX IF NOT EXISTS idx_advance_entry_id ON advance (entry_id);
CREATE INDEX IF NOT EXISTS idx_ai_access_grant_feature_key ON ai_access_grant (feature_key);
CREATE INDEX IF NOT EXISTS idx_ai_access_grant_granted_by ON ai_access_grant (granted_by);
CREATE INDEX IF NOT EXISTS idx_ai_action_run_action_key ON ai_action_run (action_key);
CREATE INDEX IF NOT EXISTS idx_ai_action_run_conversation_id ON ai_action_run (conversation_id);
CREATE INDEX IF NOT EXISTS idx_ai_action_run_user_id ON ai_action_run (user_id);
CREATE INDEX IF NOT EXISTS idx_ai_budget_period_set_by ON ai_budget_period (set_by);
CREATE INDEX IF NOT EXISTS idx_ai_conversation_user_id ON ai_conversation (user_id);
CREATE INDEX IF NOT EXISTS idx_ai_document_dossier_id ON ai_document (dossier_id);
CREATE INDEX IF NOT EXISTS idx_ai_feature_flag_last_changed_by ON ai_feature_flag (last_changed_by);
CREATE INDEX IF NOT EXISTS idx_ai_message_conversation_id ON ai_message (conversation_id);
CREATE INDEX IF NOT EXISTS idx_ai_usage_ledger_period_id ON ai_usage_ledger (period_id);
CREATE INDEX IF NOT EXISTS idx_ai_usage_ledger_user_id ON ai_usage_ledger (user_id);
CREATE INDEX IF NOT EXISTS idx_ai_vendor_credential_last_rotated_by ON ai_vendor_credential (last_rotated_by);
CREATE INDEX IF NOT EXISTS idx_app_user_employee_id ON app_user (employee_id);
CREATE INDEX IF NOT EXISTS idx_appraisal_employee_id ON appraisal (employee_id);
CREATE INDEX IF NOT EXISTS idx_appraisal_kpi_target_id ON appraisal (kpi_target_id);
CREATE INDEX IF NOT EXISTS idx_appraisal_rated_by ON appraisal (rated_by);
CREATE INDEX IF NOT EXISTS idx_approval_task_acted_by ON approval_task (acted_by);
CREATE INDEX IF NOT EXISTS idx_approval_task_assigned_user_id ON approval_task (assigned_user_id);
CREATE INDEX IF NOT EXISTS idx_approval_task_workflow_id ON approval_task (workflow_id);
CREATE INDEX IF NOT EXISTS idx_approval_task_workflow_step_id ON approval_task (workflow_step_id);
CREATE INDEX IF NOT EXISTS idx_approval_token_approval_task_id ON approval_token (approval_task_id);
CREATE INDEX IF NOT EXISTS idx_approval_token_execution_card_id ON approval_token (execution_card_id);
CREATE INDEX IF NOT EXISTS idx_asset_coa_asset_code ON asset (coa_asset_code);
CREATE INDEX IF NOT EXISTS idx_asset_coa_depr_code ON asset (coa_depr_code);
CREATE INDEX IF NOT EXISTS idx_asset_entity_id ON asset (entity_id);
CREATE INDEX IF NOT EXISTS idx_attendance_log_employee_id ON attendance_log (employee_id);
CREATE INDEX IF NOT EXISTS idx_cash_request_approver_id ON cash_request (approver_id);
CREATE INDEX IF NOT EXISTS idx_cash_request_costing_id ON cash_request (costing_id);
CREATE INDEX IF NOT EXISTS idx_cash_request_dossier_id ON cash_request (dossier_id);
CREATE INDEX IF NOT EXISTS idx_cash_request_regie_advance_id ON cash_request (regie_advance_id);
CREATE INDEX IF NOT EXISTS idx_cash_request_requested_by ON cash_request (requested_by);
CREATE INDEX IF NOT EXISTS idx_cash_request_line_cash_request_id ON cash_request_line (cash_request_id);
CREATE INDEX IF NOT EXISTS idx_cash_request_line_dictionary_item_id ON cash_request_line (dictionary_item_id);
CREATE INDEX IF NOT EXISTS idx_cash_request_line_proof_vault_id ON cash_request_line (proof_vault_id);
CREATE INDEX IF NOT EXISTS idx_cash_request_payment_cash_request_id ON cash_request_payment (cash_request_id);
CREATE INDEX IF NOT EXISTS idx_cash_request_payment_entry_id ON cash_request_payment (entry_id);
CREATE INDEX IF NOT EXISTS idx_cash_request_payment_treasury_account_id ON cash_request_payment (treasury_account_id);
CREATE INDEX IF NOT EXISTS idx_chart_of_accounts_entity_id ON chart_of_accounts (entity_id);
CREATE INDEX IF NOT EXISTS idx_client_master_client_type_id ON client_master (client_type_id);
CREATE INDEX IF NOT EXISTS idx_client_master_entity_id ON client_master (entity_id);
CREATE INDEX IF NOT EXISTS idx_close_checklist_done_by ON close_checklist (done_by);
CREATE INDEX IF NOT EXISTS idx_comms_attachment_message_id ON comms_attachment (message_id);
CREATE INDEX IF NOT EXISTS idx_comms_attachment_vault_id ON comms_attachment (vault_id);
CREATE INDEX IF NOT EXISTS idx_comms_draft_group_id ON comms_draft (group_id);
CREATE INDEX IF NOT EXISTS idx_comms_draft_user_id ON comms_draft (user_id);
CREATE INDEX IF NOT EXISTS idx_comms_group_dossier_id ON comms_group (dossier_id);
CREATE INDEX IF NOT EXISTS idx_comms_member_group_id ON comms_member (group_id);
CREATE INDEX IF NOT EXISTS idx_comms_member_user_id ON comms_member (user_id);
CREATE INDEX IF NOT EXISTS idx_comms_message_media_vault_id ON comms_message (media_vault_id);
CREATE INDEX IF NOT EXISTS idx_comms_message_sender_user_id ON comms_message (sender_user_id);
CREATE INDEX IF NOT EXISTS idx_comms_quick_reply_owner_user_id ON comms_quick_reply (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_comms_reaction_message_id ON comms_reaction (message_id);
CREATE INDEX IF NOT EXISTS idx_comms_reaction_user_id ON comms_reaction (user_id);
CREATE INDEX IF NOT EXISTS idx_comms_star_message_id ON comms_star (message_id);
CREATE INDEX IF NOT EXISTS idx_comms_star_user_id ON comms_star (user_id);
CREATE INDEX IF NOT EXISTS idx_contact_enquiry_lead_id ON contact_enquiry (lead_id);
CREATE INDEX IF NOT EXISTS idx_cost_entry_dictionary_item_id ON cost_entry (dictionary_item_id);
CREATE INDEX IF NOT EXISTS idx_cost_entry_dossier_id ON cost_entry (dossier_id);
CREATE INDEX IF NOT EXISTS idx_cost_entry_entry_id ON cost_entry (entry_id);
CREATE INDEX IF NOT EXISTS idx_costing_approver_id ON costing (approver_id);
CREATE INDEX IF NOT EXISTS idx_costing_dossier_id ON costing (dossier_id);
CREATE INDEX IF NOT EXISTS idx_costing_validator_id ON costing (validator_id);
CREATE INDEX IF NOT EXISTS idx_costing_line_costing_id ON costing_line (costing_id);
CREATE INDEX IF NOT EXISTS idx_costing_line_dictionary_item_id ON costing_line (dictionary_item_id);
CREATE INDEX IF NOT EXISTS idx_costing_line_tax_code_id ON costing_line (tax_code_id);
CREATE INDEX IF NOT EXISTS idx_cycle_count_counted_by ON cycle_count (counted_by);
CREATE INDEX IF NOT EXISTS idx_cycle_count_location_id ON cycle_count (location_id);
CREATE INDEX IF NOT EXISTS idx_debt_engagement_coa_code ON debt_engagement (coa_code);
CREATE INDEX IF NOT EXISTS idx_debt_engagement_currency ON debt_engagement (currency);
CREATE INDEX IF NOT EXISTS idx_debt_engagement_dossier_id ON debt_engagement (dossier_id);
CREATE INDEX IF NOT EXISTS idx_debt_engagement_entity_id ON debt_engagement (entity_id);
CREATE INDEX IF NOT EXISTS idx_debt_repayment_debt_engagement_id ON debt_repayment (debt_engagement_id);
CREATE INDEX IF NOT EXISTS idx_debt_repayment_entry_id ON debt_repayment (entry_id);
CREATE INDEX IF NOT EXISTS idx_delivery_note_dossier_id ON delivery_note (dossier_id);
CREATE INDEX IF NOT EXISTS idx_depreciation_schedule_entry_id ON depreciation_schedule (entry_id);
CREATE INDEX IF NOT EXISTS idx_doc_sequence_entity_id ON doc_sequence (entity_id);
CREATE INDEX IF NOT EXISTS idx_document_signature_document_vault_id ON document_signature (document_vault_id);
CREATE INDEX IF NOT EXISTS idx_document_signature_signer_user_id ON document_signature (signer_user_id);
CREATE INDEX IF NOT EXISTS idx_document_vault_verified_by ON document_vault (verified_by);
CREATE INDEX IF NOT EXISTS idx_dossier_client_id ON dossier (client_id);
CREATE INDEX IF NOT EXISTS idx_dossier_entity_id ON dossier (entity_id);
CREATE INDEX IF NOT EXISTS idx_dossier_owner_ops_id ON dossier (owner_ops_id);
CREATE INDEX IF NOT EXISTS idx_dossier_owner_sales_id ON dossier (owner_sales_id);
CREATE INDEX IF NOT EXISTS idx_dossier_service_type_id ON dossier (service_type_id);
CREATE INDEX IF NOT EXISTS idx_driver_license_document_vault_id ON driver_license (document_vault_id);
CREATE INDEX IF NOT EXISTS idx_driver_license_employee_id ON driver_license (employee_id);
CREATE INDEX IF NOT EXISTS idx_email_attachment_vault_id ON email_attachment (vault_id);
CREATE INDEX IF NOT EXISTS idx_email_connection_email_identity_id ON email_connection (email_identity_id);
CREATE INDEX IF NOT EXISTS idx_email_inbound_email_identity_id ON email_inbound (email_identity_id);
CREATE INDEX IF NOT EXISTS idx_email_send_log_document_vault_id ON email_send_log (document_vault_id);
CREATE INDEX IF NOT EXISTS idx_email_send_log_email_identity_id ON email_send_log (email_identity_id);
CREATE INDEX IF NOT EXISTS idx_employee_entity_id ON employee (entity_id);
CREATE INDEX IF NOT EXISTS idx_employee_earning_created_by ON employee_earning (created_by);
CREATE INDEX IF NOT EXISTS idx_employee_earning_employee_id ON employee_earning (employee_id);
CREATE INDEX IF NOT EXISTS idx_employee_earning_payroll_run_id ON employee_earning (payroll_run_id);
CREATE INDEX IF NOT EXISTS idx_event_log_actor_user_id ON event_log (actor_user_id);
CREATE INDEX IF NOT EXISTS idx_execution_card_created_by ON execution_card (created_by);
CREATE INDEX IF NOT EXISTS idx_extra_charge_simulation_created_by ON extra_charge_simulation (created_by);
CREATE INDEX IF NOT EXISTS idx_extra_charge_simulation_currency ON extra_charge_simulation (currency);
CREATE INDEX IF NOT EXISTS idx_extra_charge_simulation_dossier_id ON extra_charge_simulation (dossier_id);
CREATE INDEX IF NOT EXISTS idx_financial_statement_period_id ON financial_statement (period_id);
CREATE INDEX IF NOT EXISTS idx_fleet_claim_fleet_incident_id ON fleet_claim (fleet_incident_id);
CREATE INDEX IF NOT EXISTS idx_fleet_dispatch_dossier_id ON fleet_dispatch (dossier_id);
CREATE INDEX IF NOT EXISTS idx_fleet_dispatch_driver_employee_id ON fleet_dispatch (driver_employee_id);
CREATE INDEX IF NOT EXISTS idx_fleet_dispatch_vehicle_id ON fleet_dispatch (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_fleet_incident_driver_employee_id ON fleet_incident (driver_employee_id);
CREATE INDEX IF NOT EXISTS idx_fleet_incident_vehicle_id ON fleet_incident (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_fuel_log_dossier_id ON fuel_log (dossier_id);
CREATE INDEX IF NOT EXISTS idx_fuel_log_entry_id ON fuel_log (entry_id);
CREATE INDEX IF NOT EXISTS idx_fuel_log_vehicle_id ON fuel_log (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_fx_rate_daily_quote_code ON fx_rate_daily (quote_code);
CREATE INDEX IF NOT EXISTS idx_goods_received_note_entry_id ON goods_received_note (entry_id);
CREATE INDEX IF NOT EXISTS idx_goods_received_note_po_id ON goods_received_note (po_id);
CREATE INDEX IF NOT EXISTS idx_goods_received_note_received_by ON goods_received_note (received_by);
CREATE INDEX IF NOT EXISTS idx_grn_inbound_dossier_id ON grn_inbound (dossier_id);
CREATE INDEX IF NOT EXISTS idx_grn_inbound_putaway_location ON grn_inbound (putaway_location);
CREATE INDEX IF NOT EXISTS idx_hr_contract_approved_by ON hr_contract (approved_by);
CREATE INDEX IF NOT EXISTS idx_hr_contract_employee_id ON hr_contract (employee_id);
CREATE INDEX IF NOT EXISTS idx_hr_contract_pdf_vault_id ON hr_contract (pdf_vault_id);
CREATE INDEX IF NOT EXISTS idx_hr_query_issued_by ON hr_query (issued_by);
CREATE INDEX IF NOT EXISTS idx_hr_sanction_hr_query_id ON hr_sanction (hr_query_id);
CREATE INDEX IF NOT EXISTS idx_hr_sanction_issued_by ON hr_sanction (issued_by);
CREATE INDEX IF NOT EXISTS idx_inventory_item_dossier_id ON inventory_item (dossier_id);
CREATE INDEX IF NOT EXISTS idx_inventory_item_location_id ON inventory_item (location_id);
CREATE INDEX IF NOT EXISTS idx_inventory_item_owner_client_id ON inventory_item (owner_client_id);
CREATE INDEX IF NOT EXISTS idx_invoice_approved_by ON invoice (approved_by);
CREATE INDEX IF NOT EXISTS idx_invoice_entity_id ON invoice (entity_id);
CREATE INDEX IF NOT EXISTS idx_invoice_entry_id ON invoice (entry_id);
CREATE INDEX IF NOT EXISTS idx_invoice_issued_by ON invoice (issued_by);
CREATE INDEX IF NOT EXISTS idx_invoice_validated_by ON invoice (validated_by);
CREATE INDEX IF NOT EXISTS idx_invoice_line_dictionary_item_id ON invoice_line (dictionary_item_id);
CREATE INDEX IF NOT EXISTS idx_invoice_line_tax_code_id ON invoice_line (tax_code_id);
CREATE INDEX IF NOT EXISTS idx_job_applicant_cv_vault_id ON job_applicant (cv_vault_id);
CREATE INDEX IF NOT EXISTS idx_job_applicant_vacancy_id ON job_applicant (vacancy_id);
CREATE INDEX IF NOT EXISTS idx_journal_entry_attested_by ON journal_entry (attested_by);
CREATE INDEX IF NOT EXISTS idx_journal_entry_created_by ON journal_entry (created_by);
CREATE INDEX IF NOT EXISTS idx_journal_entry_entity_id ON journal_entry (entity_id);
CREATE INDEX IF NOT EXISTS idx_journal_line_dictionary_item_id ON journal_line (dictionary_item_id);
CREATE INDEX IF NOT EXISTS idx_journal_line_tax_code_id ON journal_line (tax_code_id);
CREATE INDEX IF NOT EXISTS idx_kpi_target_employee_id ON kpi_target (employee_id);
CREATE INDEX IF NOT EXISTS idx_kpi_target_set_by ON kpi_target (set_by);
CREATE INDEX IF NOT EXISTS idx_lead_client_id ON lead (client_id);
CREATE INDEX IF NOT EXISTS idx_lead_owner_user_id ON lead (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_leave_request_employee_id ON leave_request (employee_id);
CREATE INDEX IF NOT EXISTS idx_margin_simulation_created_by ON margin_simulation (created_by);
CREATE INDEX IF NOT EXISTS idx_margin_simulation_currency ON margin_simulation (currency);
CREATE INDEX IF NOT EXISTS idx_margin_simulation_dossier_id ON margin_simulation (dossier_id);
CREATE INDEX IF NOT EXISTS idx_margin_simulation_service_type_id ON margin_simulation (service_type_id);
CREATE INDEX IF NOT EXISTS idx_margin_simulation_line_dictionary_item_id ON margin_simulation_line (dictionary_item_id);
CREATE INDEX IF NOT EXISTS idx_margin_simulation_line_margin_simulation_id ON margin_simulation_line (margin_simulation_id);
CREATE INDEX IF NOT EXISTS idx_meeting_client_id ON meeting (client_id);
CREATE INDEX IF NOT EXISTS idx_meeting_lead_id ON meeting (lead_id);
CREATE INDEX IF NOT EXISTS idx_meeting_organiser_id ON meeting (organiser_id);
CREATE INDEX IF NOT EXISTS idx_meeting_transcript_vault_id ON meeting (transcript_vault_id);
CREATE INDEX IF NOT EXISTS idx_meeting_note_author_id ON meeting_note (author_id);
CREATE INDEX IF NOT EXISTS idx_meeting_note_meeting_id ON meeting_note (meeting_id);
CREATE INDEX IF NOT EXISTS idx_milestone_instance_completed_by ON milestone_instance (completed_by);
CREATE INDEX IF NOT EXISTS idx_milestone_template_stage_milestone_template_id ON milestone_template_stage (milestone_template_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_checklist_employee_id ON onboarding_checklist (employee_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_item_onboarding_checklist_id ON onboarding_item (onboarding_checklist_id);
CREATE INDEX IF NOT EXISTS idx_opportunity_client_id ON opportunity (client_id);
CREATE INDEX IF NOT EXISTS idx_opportunity_currency ON opportunity (currency);
CREATE INDEX IF NOT EXISTS idx_opportunity_dossier_id ON opportunity (dossier_id);
CREATE INDEX IF NOT EXISTS idx_opportunity_lead_id ON opportunity (lead_id);
CREATE INDEX IF NOT EXISTS idx_opportunity_owner_user_id ON opportunity (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_opportunity_pipeline_stage_id ON opportunity (pipeline_stage_id);
CREATE INDEX IF NOT EXISTS idx_outbound_line_inventory_item_id ON outbound_line (inventory_item_id);
CREATE INDEX IF NOT EXISTS idx_outbound_line_outbound_order_id ON outbound_line (outbound_order_id);
CREATE INDEX IF NOT EXISTS idx_outbound_order_client_id ON outbound_order (client_id);
CREATE INDEX IF NOT EXISTS idx_outbound_order_dossier_id ON outbound_order (dossier_id);
CREATE INDEX IF NOT EXISTS idx_payment_allocation_invoice_id ON payment_allocation (invoice_id);
CREATE INDEX IF NOT EXISTS idx_payment_allocation_receipt_id ON payment_allocation (receipt_id);
CREATE INDEX IF NOT EXISTS idx_payment_gateway_updated_by ON payment_gateway (updated_by);
CREATE INDEX IF NOT EXISTS idx_payment_receipt_client_id ON payment_receipt (client_id);
CREATE INDEX IF NOT EXISTS idx_payment_receipt_entry_id ON payment_receipt (entry_id);
CREATE INDEX IF NOT EXISTS idx_payment_receipt_treasury_account_id ON payment_receipt (treasury_account_id);
CREATE INDEX IF NOT EXISTS idx_payroll_component_coa_code ON payroll_component (coa_code);
CREATE INDEX IF NOT EXISTS idx_payroll_component_tax_code_id ON payroll_component (tax_code_id);
CREATE INDEX IF NOT EXISTS idx_payroll_run_entry_id ON payroll_run (entry_id);
CREATE INDEX IF NOT EXISTS idx_payroll_run_item_employee_id ON payroll_run_item (employee_id);
CREATE INDEX IF NOT EXISTS idx_payroll_run_item_payroll_run_id ON payroll_run_item (payroll_run_id);
CREATE INDEX IF NOT EXISTS idx_portal_access_client_id ON portal_access (client_id);
CREATE INDEX IF NOT EXISTS idx_posting_rule_credit_account ON posting_rule (credit_account);
CREATE INDEX IF NOT EXISTS idx_posting_rule_debit_account ON posting_rule (debit_account);
CREATE INDEX IF NOT EXISTS idx_posting_rule_tax_code_id ON posting_rule (tax_code_id);
CREATE INDEX IF NOT EXISTS idx_pricing_variance_costing_id ON pricing_variance (costing_id);
CREATE INDEX IF NOT EXISTS idx_pricing_variance_dossier_id ON pricing_variance (dossier_id);
CREATE INDEX IF NOT EXISTS idx_pricing_variance_margin_simulation_id ON pricing_variance (margin_simulation_id);
CREATE INDEX IF NOT EXISTS idx_pricing_variance_quotation_id ON pricing_variance (quotation_id);
CREATE INDEX IF NOT EXISTS idx_proposal_client_id ON proposal (client_id);
CREATE INDEX IF NOT EXISTS idx_proposal_lead_id ON proposal (lead_id);
CREATE INDEX IF NOT EXISTS idx_proposal_opportunity_id ON proposal (opportunity_id);
CREATE INDEX IF NOT EXISTS idx_proposal_pdf_vault_id ON proposal (pdf_vault_id);
CREATE INDEX IF NOT EXISTS idx_proposal_reviewed_by ON proposal (reviewed_by);
CREATE INDEX IF NOT EXISTS idx_proposal_line_dictionary_item_id ON proposal_line (dictionary_item_id);
CREATE INDEX IF NOT EXISTS idx_proposal_line_proposal_id ON proposal_line (proposal_id);
CREATE INDEX IF NOT EXISTS idx_proposal_narrative_proposal_id ON proposal_narrative (proposal_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_approver_id ON purchase_order (approver_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_dossier_id ON purchase_order (dossier_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_issuer_id ON purchase_order (issuer_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_pr_id ON purchase_order (pr_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_supplier_id ON purchase_order (supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_item_dictionary_item_id ON purchase_order_item (dictionary_item_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_item_po_id ON purchase_order_item (po_id);
CREATE INDEX IF NOT EXISTS idx_purchase_request_requested_by ON purchase_request (requested_by);
CREATE INDEX IF NOT EXISTS idx_q_ticket_dossier_id ON q_ticket (dossier_id);
CREATE INDEX IF NOT EXISTS idx_q_ticket_milestone_instance_id ON q_ticket (milestone_instance_id);
CREATE INDEX IF NOT EXISTS idx_quotation_client_id ON quotation (client_id);
CREATE INDEX IF NOT EXISTS idx_quotation_costing_id ON quotation (costing_id);
CREATE INDEX IF NOT EXISTS idx_quotation_currency ON quotation (currency);
CREATE INDEX IF NOT EXISTS idx_quotation_dossier_id ON quotation (dossier_id);
CREATE INDEX IF NOT EXISTS idx_quotation_entity_id ON quotation (entity_id);
CREATE INDEX IF NOT EXISTS idx_quotation_opportunity_id ON quotation (opportunity_id);
CREATE INDEX IF NOT EXISTS idx_quotation_pdf_vault_id ON quotation (pdf_vault_id);
CREATE INDEX IF NOT EXISTS idx_quotation_line_dictionary_item_id ON quotation_line (dictionary_item_id);
CREATE INDEX IF NOT EXISTS idx_quotation_line_quotation_id ON quotation_line (quotation_id);
CREATE INDEX IF NOT EXISTS idx_quotation_line_tax_code_id ON quotation_line (tax_code_id);
CREATE INDEX IF NOT EXISTS idx_regie_advance_holder_user_id ON regie_advance (holder_user_id);
CREATE INDEX IF NOT EXISTS idx_regie_advance_issue_entry_id ON regie_advance (issue_entry_id);
CREATE INDEX IF NOT EXISTS idx_reminder_user_id ON reminder (user_id);
CREATE INDEX IF NOT EXISTS idx_saved_report_owner_user_id ON saved_report (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_report_created_by ON scheduled_report (created_by);
CREATE INDEX IF NOT EXISTS idx_scope_parent_scope_id ON scope (parent_scope_id);
CREATE INDEX IF NOT EXISTS idx_setting_updated_by ON setting (updated_by);
CREATE INDEX IF NOT EXISTS idx_soft_delete_deleted_by ON soft_delete (deleted_by);
CREATE INDEX IF NOT EXISTS idx_soft_delete_restore_requested_by ON soft_delete (restore_requested_by);
CREATE INDEX IF NOT EXISTS idx_soft_delete_restored_by ON soft_delete (restored_by);
CREATE INDEX IF NOT EXISTS idx_sop_document_vault_id ON sop_document (vault_id);
CREATE INDEX IF NOT EXISTS idx_stock_movement_from_location ON stock_movement (from_location);
CREATE INDEX IF NOT EXISTS idx_stock_movement_inventory_item_id ON stock_movement (inventory_item_id);
CREATE INDEX IF NOT EXISTS idx_stock_movement_moved_by ON stock_movement (moved_by);
CREATE INDEX IF NOT EXISTS idx_stock_movement_to_location ON stock_movement (to_location);
CREATE INDEX IF NOT EXISTS idx_success_story_dossier_id ON success_story (dossier_id);
CREATE INDEX IF NOT EXISTS idx_success_story_signed_off_by ON success_story (signed_off_by);
CREATE INDEX IF NOT EXISTS idx_succession_plan_incumbent_id ON succession_plan (incumbent_id);
CREATE INDEX IF NOT EXISTS idx_succession_plan_successor_id ON succession_plan (successor_id);
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_currency ON supplier_invoice (currency);
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_dossier_id ON supplier_invoice (dossier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_entity_id ON supplier_invoice (entity_id);
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_entry_id ON supplier_invoice (entry_id);
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_grn_id ON supplier_invoice (grn_id);
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_po_id ON supplier_invoice (po_id);
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_supplier_id ON supplier_invoice (supplier_id);
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_line_dictionary_item_id ON supplier_invoice_line (dictionary_item_id);
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_line_expense_account ON supplier_invoice_line (expense_account);
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_line_supplier_invoice_id ON supplier_invoice_line (supplier_invoice_id);
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_line_tax_code_id ON supplier_invoice_line (tax_code_id);
CREATE INDEX IF NOT EXISTS idx_supplier_master_entity_id ON supplier_master (entity_id);
CREATE INDEX IF NOT EXISTS idx_talent_pool_applicant_id ON talent_pool (applicant_id);
CREATE INDEX IF NOT EXISTS idx_tax_calendar_entity_id ON tax_calendar (entity_id);
CREATE INDEX IF NOT EXISTS idx_tax_calendar_tax_declaration_id ON tax_calendar (tax_declaration_id);
CREATE INDEX IF NOT EXISTS idx_tax_code_posts_credit_account ON tax_code (posts_credit_account);
CREATE INDEX IF NOT EXISTS idx_tax_code_posts_debit_account ON tax_code (posts_debit_account);
CREATE INDEX IF NOT EXISTS idx_training_attendance_certificate_vault_id ON training_attendance (certificate_vault_id);
CREATE INDEX IF NOT EXISTS idx_training_attendance_employee_id ON training_attendance (employee_id);
CREATE INDEX IF NOT EXISTS idx_training_attendance_training_id ON training_attendance (training_id);
CREATE INDEX IF NOT EXISTS idx_transit_order_dossier_id ON transit_order (dossier_id);
CREATE INDEX IF NOT EXISTS idx_treasury_account_coa_code ON treasury_account (coa_code);
CREATE INDEX IF NOT EXISTS idx_treasury_account_entity_id ON treasury_account (entity_id);
CREATE INDEX IF NOT EXISTS idx_treasury_account_momo_fee_account ON treasury_account (momo_fee_account);
CREATE INDEX IF NOT EXISTS idx_user_capability_capability_id ON user_capability (capability_id);
CREATE INDEX IF NOT EXISTS idx_user_capability_user_id ON user_capability (user_id);
CREATE INDEX IF NOT EXISTS idx_user_role_role_id ON user_role (role_id);
CREATE INDEX IF NOT EXISTS idx_user_role_user_id ON user_role (user_id);
CREATE INDEX IF NOT EXISTS idx_user_scope_scope_id ON user_scope (scope_id);
CREATE INDEX IF NOT EXISTS idx_user_scope_user_id ON user_scope (user_id);
CREATE INDEX IF NOT EXISTS idx_user_session_killed_by ON user_session (killed_by);
CREATE INDEX IF NOT EXISTS idx_vehicle_asset_id ON vehicle (asset_id);
CREATE INDEX IF NOT EXISTS idx_vehicle_entity_id ON vehicle (entity_id);
CREATE INDEX IF NOT EXISTS idx_vehicle_compliance_vehicle_id ON vehicle_compliance (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_wms_equipment_asset_id ON wms_equipment (asset_id);
CREATE INDEX IF NOT EXISTS idx_wms_equipment_assigned_to ON wms_equipment (assigned_to);
CREATE INDEX IF NOT EXISTS idx_wms_equipment_location_id ON wms_equipment (location_id);
CREATE INDEX IF NOT EXISTS idx_work_order_dossier_id ON work_order (dossier_id);
CREATE INDEX IF NOT EXISTS idx_work_order_entry_id ON work_order (entry_id);
CREATE INDEX IF NOT EXISTS idx_work_order_vehicle_id ON work_order (vehicle_id);
CREATE INDEX IF NOT EXISTS idx_work_order_wms_equipment_id ON work_order (wms_equipment_id);
CREATE INDEX IF NOT EXISTS idx_work_order_part_inventory_item_id ON work_order_part (inventory_item_id);
CREATE INDEX IF NOT EXISTS idx_work_order_part_work_order_id ON work_order_part (work_order_id);
CREATE INDEX IF NOT EXISTS idx_workflow_event_type_id ON workflow (event_type_id);
CREATE INDEX IF NOT EXISTS idx_workflow_step_role_id ON workflow_step (role_id);
CREATE INDEX IF NOT EXISTS idx_workflow_step_scope_id ON workflow_step (scope_id);

-- DOWN
-- Fully reversible: dropping an index loses no data, it only restores the
-- sequential scans on every FK check and every child lookup.
--
-- DROP INDEX IF EXISTS idx_access_review_completed_by;
-- DROP INDEX IF EXISTS idx_access_review_created_by;
-- DROP INDEX IF EXISTS idx_access_review_entry_decided_by;
-- DROP INDEX IF EXISTS idx_access_review_entry_user_id;
-- DROP INDEX IF EXISTS idx_advance_client_id;
-- DROP INDEX IF EXISTS idx_advance_dossier_id;
-- DROP INDEX IF EXISTS idx_advance_entry_id;
-- DROP INDEX IF EXISTS idx_ai_access_grant_feature_key;
-- DROP INDEX IF EXISTS idx_ai_access_grant_granted_by;
-- DROP INDEX IF EXISTS idx_ai_action_run_action_key;
-- DROP INDEX IF EXISTS idx_ai_action_run_conversation_id;
-- DROP INDEX IF EXISTS idx_ai_action_run_user_id;
-- DROP INDEX IF EXISTS idx_ai_budget_period_set_by;
-- DROP INDEX IF EXISTS idx_ai_conversation_user_id;
-- DROP INDEX IF EXISTS idx_ai_document_dossier_id;
-- DROP INDEX IF EXISTS idx_ai_feature_flag_last_changed_by;
-- DROP INDEX IF EXISTS idx_ai_message_conversation_id;
-- DROP INDEX IF EXISTS idx_ai_usage_ledger_period_id;
-- DROP INDEX IF EXISTS idx_ai_usage_ledger_user_id;
-- DROP INDEX IF EXISTS idx_ai_vendor_credential_last_rotated_by;
-- DROP INDEX IF EXISTS idx_app_user_employee_id;
-- DROP INDEX IF EXISTS idx_appraisal_employee_id;
-- DROP INDEX IF EXISTS idx_appraisal_kpi_target_id;
-- DROP INDEX IF EXISTS idx_appraisal_rated_by;
-- DROP INDEX IF EXISTS idx_approval_task_acted_by;
-- DROP INDEX IF EXISTS idx_approval_task_assigned_user_id;
-- DROP INDEX IF EXISTS idx_approval_task_workflow_id;
-- DROP INDEX IF EXISTS idx_approval_task_workflow_step_id;
-- DROP INDEX IF EXISTS idx_approval_token_approval_task_id;
-- DROP INDEX IF EXISTS idx_approval_token_execution_card_id;
-- DROP INDEX IF EXISTS idx_asset_coa_asset_code;
-- DROP INDEX IF EXISTS idx_asset_coa_depr_code;
-- DROP INDEX IF EXISTS idx_asset_entity_id;
-- DROP INDEX IF EXISTS idx_attendance_log_employee_id;
-- DROP INDEX IF EXISTS idx_cash_request_approver_id;
-- DROP INDEX IF EXISTS idx_cash_request_costing_id;
-- DROP INDEX IF EXISTS idx_cash_request_dossier_id;
-- DROP INDEX IF EXISTS idx_cash_request_regie_advance_id;
-- DROP INDEX IF EXISTS idx_cash_request_requested_by;
-- DROP INDEX IF EXISTS idx_cash_request_line_cash_request_id;
-- DROP INDEX IF EXISTS idx_cash_request_line_dictionary_item_id;
-- DROP INDEX IF EXISTS idx_cash_request_line_proof_vault_id;
-- DROP INDEX IF EXISTS idx_cash_request_payment_cash_request_id;
-- DROP INDEX IF EXISTS idx_cash_request_payment_entry_id;
-- DROP INDEX IF EXISTS idx_cash_request_payment_treasury_account_id;
-- DROP INDEX IF EXISTS idx_chart_of_accounts_entity_id;
-- DROP INDEX IF EXISTS idx_client_master_client_type_id;
-- DROP INDEX IF EXISTS idx_client_master_entity_id;
-- DROP INDEX IF EXISTS idx_close_checklist_done_by;
-- DROP INDEX IF EXISTS idx_comms_attachment_message_id;
-- DROP INDEX IF EXISTS idx_comms_attachment_vault_id;
-- DROP INDEX IF EXISTS idx_comms_draft_group_id;
-- DROP INDEX IF EXISTS idx_comms_draft_user_id;
-- DROP INDEX IF EXISTS idx_comms_group_dossier_id;
-- DROP INDEX IF EXISTS idx_comms_member_group_id;
-- DROP INDEX IF EXISTS idx_comms_member_user_id;
-- DROP INDEX IF EXISTS idx_comms_message_media_vault_id;
-- DROP INDEX IF EXISTS idx_comms_message_sender_user_id;
-- DROP INDEX IF EXISTS idx_comms_quick_reply_owner_user_id;
-- DROP INDEX IF EXISTS idx_comms_reaction_message_id;
-- DROP INDEX IF EXISTS idx_comms_reaction_user_id;
-- DROP INDEX IF EXISTS idx_comms_star_message_id;
-- DROP INDEX IF EXISTS idx_comms_star_user_id;
-- DROP INDEX IF EXISTS idx_contact_enquiry_lead_id;
-- DROP INDEX IF EXISTS idx_cost_entry_dictionary_item_id;
-- DROP INDEX IF EXISTS idx_cost_entry_dossier_id;
-- DROP INDEX IF EXISTS idx_cost_entry_entry_id;
-- DROP INDEX IF EXISTS idx_costing_approver_id;
-- DROP INDEX IF EXISTS idx_costing_dossier_id;
-- DROP INDEX IF EXISTS idx_costing_validator_id;
-- DROP INDEX IF EXISTS idx_costing_line_costing_id;
-- DROP INDEX IF EXISTS idx_costing_line_dictionary_item_id;
-- DROP INDEX IF EXISTS idx_costing_line_tax_code_id;
-- DROP INDEX IF EXISTS idx_cycle_count_counted_by;
-- DROP INDEX IF EXISTS idx_cycle_count_location_id;
-- DROP INDEX IF EXISTS idx_debt_engagement_coa_code;
-- DROP INDEX IF EXISTS idx_debt_engagement_currency;
-- DROP INDEX IF EXISTS idx_debt_engagement_dossier_id;
-- DROP INDEX IF EXISTS idx_debt_engagement_entity_id;
-- DROP INDEX IF EXISTS idx_debt_repayment_debt_engagement_id;
-- DROP INDEX IF EXISTS idx_debt_repayment_entry_id;
-- DROP INDEX IF EXISTS idx_delivery_note_dossier_id;
-- DROP INDEX IF EXISTS idx_depreciation_schedule_entry_id;
-- DROP INDEX IF EXISTS idx_doc_sequence_entity_id;
-- DROP INDEX IF EXISTS idx_document_signature_document_vault_id;
-- DROP INDEX IF EXISTS idx_document_signature_signer_user_id;
-- DROP INDEX IF EXISTS idx_document_vault_verified_by;
-- DROP INDEX IF EXISTS idx_dossier_client_id;
-- DROP INDEX IF EXISTS idx_dossier_entity_id;
-- DROP INDEX IF EXISTS idx_dossier_owner_ops_id;
-- DROP INDEX IF EXISTS idx_dossier_owner_sales_id;
-- DROP INDEX IF EXISTS idx_dossier_service_type_id;
-- DROP INDEX IF EXISTS idx_driver_license_document_vault_id;
-- DROP INDEX IF EXISTS idx_driver_license_employee_id;
-- DROP INDEX IF EXISTS idx_email_attachment_vault_id;
-- DROP INDEX IF EXISTS idx_email_connection_email_identity_id;
-- DROP INDEX IF EXISTS idx_email_inbound_email_identity_id;
-- DROP INDEX IF EXISTS idx_email_send_log_document_vault_id;
-- DROP INDEX IF EXISTS idx_email_send_log_email_identity_id;
-- DROP INDEX IF EXISTS idx_employee_entity_id;
-- DROP INDEX IF EXISTS idx_employee_earning_created_by;
-- DROP INDEX IF EXISTS idx_employee_earning_employee_id;
-- DROP INDEX IF EXISTS idx_employee_earning_payroll_run_id;
-- DROP INDEX IF EXISTS idx_event_log_actor_user_id;
-- DROP INDEX IF EXISTS idx_execution_card_created_by;
-- DROP INDEX IF EXISTS idx_extra_charge_simulation_created_by;
-- DROP INDEX IF EXISTS idx_extra_charge_simulation_currency;
-- DROP INDEX IF EXISTS idx_extra_charge_simulation_dossier_id;
-- DROP INDEX IF EXISTS idx_financial_statement_period_id;
-- DROP INDEX IF EXISTS idx_fleet_claim_fleet_incident_id;
-- DROP INDEX IF EXISTS idx_fleet_dispatch_dossier_id;
-- DROP INDEX IF EXISTS idx_fleet_dispatch_driver_employee_id;
-- DROP INDEX IF EXISTS idx_fleet_dispatch_vehicle_id;
-- DROP INDEX IF EXISTS idx_fleet_incident_driver_employee_id;
-- DROP INDEX IF EXISTS idx_fleet_incident_vehicle_id;
-- DROP INDEX IF EXISTS idx_fuel_log_dossier_id;
-- DROP INDEX IF EXISTS idx_fuel_log_entry_id;
-- DROP INDEX IF EXISTS idx_fuel_log_vehicle_id;
-- DROP INDEX IF EXISTS idx_fx_rate_daily_quote_code;
-- DROP INDEX IF EXISTS idx_goods_received_note_entry_id;
-- DROP INDEX IF EXISTS idx_goods_received_note_po_id;
-- DROP INDEX IF EXISTS idx_goods_received_note_received_by;
-- DROP INDEX IF EXISTS idx_grn_inbound_dossier_id;
-- DROP INDEX IF EXISTS idx_grn_inbound_putaway_location;
-- DROP INDEX IF EXISTS idx_hr_contract_approved_by;
-- DROP INDEX IF EXISTS idx_hr_contract_employee_id;
-- DROP INDEX IF EXISTS idx_hr_contract_pdf_vault_id;
-- DROP INDEX IF EXISTS idx_hr_query_issued_by;
-- DROP INDEX IF EXISTS idx_hr_sanction_hr_query_id;
-- DROP INDEX IF EXISTS idx_hr_sanction_issued_by;
-- DROP INDEX IF EXISTS idx_inventory_item_dossier_id;
-- DROP INDEX IF EXISTS idx_inventory_item_location_id;
-- DROP INDEX IF EXISTS idx_inventory_item_owner_client_id;
-- DROP INDEX IF EXISTS idx_invoice_approved_by;
-- DROP INDEX IF EXISTS idx_invoice_entity_id;
-- DROP INDEX IF EXISTS idx_invoice_entry_id;
-- DROP INDEX IF EXISTS idx_invoice_issued_by;
-- DROP INDEX IF EXISTS idx_invoice_validated_by;
-- DROP INDEX IF EXISTS idx_invoice_line_dictionary_item_id;
-- DROP INDEX IF EXISTS idx_invoice_line_tax_code_id;
-- DROP INDEX IF EXISTS idx_job_applicant_cv_vault_id;
-- DROP INDEX IF EXISTS idx_job_applicant_vacancy_id;
-- DROP INDEX IF EXISTS idx_journal_entry_attested_by;
-- DROP INDEX IF EXISTS idx_journal_entry_created_by;
-- DROP INDEX IF EXISTS idx_journal_entry_entity_id;
-- DROP INDEX IF EXISTS idx_journal_line_dictionary_item_id;
-- DROP INDEX IF EXISTS idx_journal_line_tax_code_id;
-- DROP INDEX IF EXISTS idx_kpi_target_employee_id;
-- DROP INDEX IF EXISTS idx_kpi_target_set_by;
-- DROP INDEX IF EXISTS idx_lead_client_id;
-- DROP INDEX IF EXISTS idx_lead_owner_user_id;
-- DROP INDEX IF EXISTS idx_leave_request_employee_id;
-- DROP INDEX IF EXISTS idx_margin_simulation_created_by;
-- DROP INDEX IF EXISTS idx_margin_simulation_currency;
-- DROP INDEX IF EXISTS idx_margin_simulation_dossier_id;
-- DROP INDEX IF EXISTS idx_margin_simulation_service_type_id;
-- DROP INDEX IF EXISTS idx_margin_simulation_line_dictionary_item_id;
-- DROP INDEX IF EXISTS idx_margin_simulation_line_margin_simulation_id;
-- DROP INDEX IF EXISTS idx_meeting_client_id;
-- DROP INDEX IF EXISTS idx_meeting_lead_id;
-- DROP INDEX IF EXISTS idx_meeting_organiser_id;
-- DROP INDEX IF EXISTS idx_meeting_transcript_vault_id;
-- DROP INDEX IF EXISTS idx_meeting_note_author_id;
-- DROP INDEX IF EXISTS idx_meeting_note_meeting_id;
-- DROP INDEX IF EXISTS idx_milestone_instance_completed_by;
-- DROP INDEX IF EXISTS idx_milestone_template_stage_milestone_template_id;
-- DROP INDEX IF EXISTS idx_onboarding_checklist_employee_id;
-- DROP INDEX IF EXISTS idx_onboarding_item_onboarding_checklist_id;
-- DROP INDEX IF EXISTS idx_opportunity_client_id;
-- DROP INDEX IF EXISTS idx_opportunity_currency;
-- DROP INDEX IF EXISTS idx_opportunity_dossier_id;
-- DROP INDEX IF EXISTS idx_opportunity_lead_id;
-- DROP INDEX IF EXISTS idx_opportunity_owner_user_id;
-- DROP INDEX IF EXISTS idx_opportunity_pipeline_stage_id;
-- DROP INDEX IF EXISTS idx_outbound_line_inventory_item_id;
-- DROP INDEX IF EXISTS idx_outbound_line_outbound_order_id;
-- DROP INDEX IF EXISTS idx_outbound_order_client_id;
-- DROP INDEX IF EXISTS idx_outbound_order_dossier_id;
-- DROP INDEX IF EXISTS idx_payment_allocation_invoice_id;
-- DROP INDEX IF EXISTS idx_payment_allocation_receipt_id;
-- DROP INDEX IF EXISTS idx_payment_gateway_updated_by;
-- DROP INDEX IF EXISTS idx_payment_receipt_client_id;
-- DROP INDEX IF EXISTS idx_payment_receipt_entry_id;
-- DROP INDEX IF EXISTS idx_payment_receipt_treasury_account_id;
-- DROP INDEX IF EXISTS idx_payroll_component_coa_code;
-- DROP INDEX IF EXISTS idx_payroll_component_tax_code_id;
-- DROP INDEX IF EXISTS idx_payroll_run_entry_id;
-- DROP INDEX IF EXISTS idx_payroll_run_item_employee_id;
-- DROP INDEX IF EXISTS idx_payroll_run_item_payroll_run_id;
-- DROP INDEX IF EXISTS idx_portal_access_client_id;
-- DROP INDEX IF EXISTS idx_posting_rule_credit_account;
-- DROP INDEX IF EXISTS idx_posting_rule_debit_account;
-- DROP INDEX IF EXISTS idx_posting_rule_tax_code_id;
-- DROP INDEX IF EXISTS idx_pricing_variance_costing_id;
-- DROP INDEX IF EXISTS idx_pricing_variance_dossier_id;
-- DROP INDEX IF EXISTS idx_pricing_variance_margin_simulation_id;
-- DROP INDEX IF EXISTS idx_pricing_variance_quotation_id;
-- DROP INDEX IF EXISTS idx_proposal_client_id;
-- DROP INDEX IF EXISTS idx_proposal_lead_id;
-- DROP INDEX IF EXISTS idx_proposal_opportunity_id;
-- DROP INDEX IF EXISTS idx_proposal_pdf_vault_id;
-- DROP INDEX IF EXISTS idx_proposal_reviewed_by;
-- DROP INDEX IF EXISTS idx_proposal_line_dictionary_item_id;
-- DROP INDEX IF EXISTS idx_proposal_line_proposal_id;
-- DROP INDEX IF EXISTS idx_proposal_narrative_proposal_id;
-- DROP INDEX IF EXISTS idx_purchase_order_approver_id;
-- DROP INDEX IF EXISTS idx_purchase_order_dossier_id;
-- DROP INDEX IF EXISTS idx_purchase_order_issuer_id;
-- DROP INDEX IF EXISTS idx_purchase_order_pr_id;
-- DROP INDEX IF EXISTS idx_purchase_order_supplier_id;
-- DROP INDEX IF EXISTS idx_purchase_order_item_dictionary_item_id;
-- DROP INDEX IF EXISTS idx_purchase_order_item_po_id;
-- DROP INDEX IF EXISTS idx_purchase_request_requested_by;
-- DROP INDEX IF EXISTS idx_q_ticket_dossier_id;
-- DROP INDEX IF EXISTS idx_q_ticket_milestone_instance_id;
-- DROP INDEX IF EXISTS idx_quotation_client_id;
-- DROP INDEX IF EXISTS idx_quotation_costing_id;
-- DROP INDEX IF EXISTS idx_quotation_currency;
-- DROP INDEX IF EXISTS idx_quotation_dossier_id;
-- DROP INDEX IF EXISTS idx_quotation_entity_id;
-- DROP INDEX IF EXISTS idx_quotation_opportunity_id;
-- DROP INDEX IF EXISTS idx_quotation_pdf_vault_id;
-- DROP INDEX IF EXISTS idx_quotation_line_dictionary_item_id;
-- DROP INDEX IF EXISTS idx_quotation_line_quotation_id;
-- DROP INDEX IF EXISTS idx_quotation_line_tax_code_id;
-- DROP INDEX IF EXISTS idx_regie_advance_holder_user_id;
-- DROP INDEX IF EXISTS idx_regie_advance_issue_entry_id;
-- DROP INDEX IF EXISTS idx_reminder_user_id;
-- DROP INDEX IF EXISTS idx_saved_report_owner_user_id;
-- DROP INDEX IF EXISTS idx_scheduled_report_created_by;
-- DROP INDEX IF EXISTS idx_scope_parent_scope_id;
-- DROP INDEX IF EXISTS idx_setting_updated_by;
-- DROP INDEX IF EXISTS idx_soft_delete_deleted_by;
-- DROP INDEX IF EXISTS idx_soft_delete_restore_requested_by;
-- DROP INDEX IF EXISTS idx_soft_delete_restored_by;
-- DROP INDEX IF EXISTS idx_sop_document_vault_id;
-- DROP INDEX IF EXISTS idx_stock_movement_from_location;
-- DROP INDEX IF EXISTS idx_stock_movement_inventory_item_id;
-- DROP INDEX IF EXISTS idx_stock_movement_moved_by;
-- DROP INDEX IF EXISTS idx_stock_movement_to_location;
-- DROP INDEX IF EXISTS idx_success_story_dossier_id;
-- DROP INDEX IF EXISTS idx_success_story_signed_off_by;
-- DROP INDEX IF EXISTS idx_succession_plan_incumbent_id;
-- DROP INDEX IF EXISTS idx_succession_plan_successor_id;
-- DROP INDEX IF EXISTS idx_supplier_invoice_currency;
-- DROP INDEX IF EXISTS idx_supplier_invoice_dossier_id;
-- DROP INDEX IF EXISTS idx_supplier_invoice_entity_id;
-- DROP INDEX IF EXISTS idx_supplier_invoice_entry_id;
-- DROP INDEX IF EXISTS idx_supplier_invoice_grn_id;
-- DROP INDEX IF EXISTS idx_supplier_invoice_po_id;
-- DROP INDEX IF EXISTS idx_supplier_invoice_supplier_id;
-- DROP INDEX IF EXISTS idx_supplier_invoice_line_dictionary_item_id;
-- DROP INDEX IF EXISTS idx_supplier_invoice_line_expense_account;
-- DROP INDEX IF EXISTS idx_supplier_invoice_line_supplier_invoice_id;
-- DROP INDEX IF EXISTS idx_supplier_invoice_line_tax_code_id;
-- DROP INDEX IF EXISTS idx_supplier_master_entity_id;
-- DROP INDEX IF EXISTS idx_talent_pool_applicant_id;
-- DROP INDEX IF EXISTS idx_tax_calendar_entity_id;
-- DROP INDEX IF EXISTS idx_tax_calendar_tax_declaration_id;
-- DROP INDEX IF EXISTS idx_tax_code_posts_credit_account;
-- DROP INDEX IF EXISTS idx_tax_code_posts_debit_account;
-- DROP INDEX IF EXISTS idx_training_attendance_certificate_vault_id;
-- DROP INDEX IF EXISTS idx_training_attendance_employee_id;
-- DROP INDEX IF EXISTS idx_training_attendance_training_id;
-- DROP INDEX IF EXISTS idx_transit_order_dossier_id;
-- DROP INDEX IF EXISTS idx_treasury_account_coa_code;
-- DROP INDEX IF EXISTS idx_treasury_account_entity_id;
-- DROP INDEX IF EXISTS idx_treasury_account_momo_fee_account;
-- DROP INDEX IF EXISTS idx_user_capability_capability_id;
-- DROP INDEX IF EXISTS idx_user_capability_user_id;
-- DROP INDEX IF EXISTS idx_user_role_role_id;
-- DROP INDEX IF EXISTS idx_user_role_user_id;
-- DROP INDEX IF EXISTS idx_user_scope_scope_id;
-- DROP INDEX IF EXISTS idx_user_scope_user_id;
-- DROP INDEX IF EXISTS idx_user_session_killed_by;
-- DROP INDEX IF EXISTS idx_vehicle_asset_id;
-- DROP INDEX IF EXISTS idx_vehicle_entity_id;
-- DROP INDEX IF EXISTS idx_vehicle_compliance_vehicle_id;
-- DROP INDEX IF EXISTS idx_wms_equipment_asset_id;
-- DROP INDEX IF EXISTS idx_wms_equipment_assigned_to;
-- DROP INDEX IF EXISTS idx_wms_equipment_location_id;
-- DROP INDEX IF EXISTS idx_work_order_dossier_id;
-- DROP INDEX IF EXISTS idx_work_order_entry_id;
-- DROP INDEX IF EXISTS idx_work_order_vehicle_id;
-- DROP INDEX IF EXISTS idx_work_order_wms_equipment_id;
-- DROP INDEX IF EXISTS idx_work_order_part_inventory_item_id;
-- DROP INDEX IF EXISTS idx_work_order_part_work_order_id;
-- DROP INDEX IF EXISTS idx_workflow_event_type_id;
-- DROP INDEX IF EXISTS idx_workflow_step_role_id;
-- DROP INDEX IF EXISTS idx_workflow_step_scope_id;
