"use strict";
jest.mock("../../src/modules/sales/proposal/proposal.repo",()=>({byShareHash:jest.fn(),listLines:jest.fn(),listNarratives:jest.fn(),stampViewed:jest.fn(),stampDownloaded:jest.fn()}));
jest.mock("../../src/modules/vault/document_vault/document_vault.service",()=>({fetchBytes:jest.fn()}));
const repo=require("../../src/modules/sales/proposal/proposal.repo");const vault=require("../../src/modules/vault/document_vault/document_vault.service");const service=require("../../src/modules/sales/proposal_public/proposal_public.service");
const live={proposal_id:"p1",status:"SENT",share_expires_at:"2099-01-01",share_revoked_at:null,pdf_vault_id:"d1",client_id:null};
beforeEach(()=>{jest.clearAllMocks();repo.byShareHash.mockResolvedValue({...live});repo.listLines.mockResolvedValue([{label:"Freight",qty:1,unit_price:2,dictionary_item_id:"secret"}]);repo.listNarratives.mockResolvedValue([{section:"scope",language:"EN",body:"Body",raw_pain_points:"secret"}]);});
describe("F5 public proposal",()=>{
 test("returns an explicit allow-list and stamps the first view",async()=>{const out=await service.get({query:jest.fn().mockResolvedValue({rows:[]})},"token");expect(out.lines[0]).toEqual({label:"Freight",qty:1,unit_price:2});expect(out.narratives[0]).toEqual({section:"scope",language:"EN",body:"Body",sort_order:undefined});expect(repo.stampViewed).toHaveBeenCalledWith(expect.anything(),"p1");});
 test.each([{...live,share_expires_at:"2000-01-01"},{...live,share_revoked_at:"2026-01-01"},{...live,status:"DRAFT"},null])("expired, revoked, unsent and unknown all give the same 404",async row=>{repo.byShareHash.mockResolvedValue(row);await expect(service.resolve({},"token")).rejects.toMatchObject({code:"NOT_FOUND",status:404});});
 test("download is server bytes and stamps engagement",async()=>{vault.fetchBytes.mockResolvedValue({doc:{doc_number:"P-1"},buffer:Buffer.from("pdf")});expect((await service.download({},"token")).buffer.toString()).toBe("pdf");expect(repo.stampDownloaded).toHaveBeenCalledWith({},"p1");});
 test("implementation signs 256-bit random tokens, rate-limits public reads and renders server PDF",()=>{const proposal=require("fs").readFileSync(require("path").join(__dirname,"../../src/modules/sales/proposal/proposal.service.js"),"utf8");const routes=require("fs").readFileSync(require("path").join(__dirname,"../../src/modules/sales/proposal_public/proposal_public.routes.js"),"utf8");expect(proposal).toContain("randomBytes(32)");expect(proposal).toContain("createHmac");expect(proposal).toContain("renderAndStore");expect(routes).toContain("makeLimiter");});
 test("migration provides entropy lifecycle and engagement columns",()=>{const sql=require("fs").readFileSync(require("path").join(__dirname,"../../migrations/tenant/0692_sales_crm_f5_proposal_sharing.sql"),"utf8");for(const k of ["share_token_hash","share_expires_at","share_revoked_at","viewed_at","downloaded_at"])expect(sql).toContain(k);});
});
